config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :blog do
    collection do
      get :test
    end
  end
  root 'blog#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :label_blogs
  has_many :labels, through: :label_blogs
  acts_as_paranoid without_default_scope: true

  class << self
    def test
      t = Thread.new do
        loop{p "新线程"}
      end
      t.join
      p "主线程"
    end

  end
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_many :label_blogs
  has_many :blogs, through: :label_blogs
  acts_as_paranoid without_default_scope: true


end

app/models/label_blog.rb
class LabelBlog < ActiveRecord::Base
  has_many :label_blogs
  has_many :blogs, through: :label_blogs
  acts_as_paranoid without_default_scope: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
# -*- encoding : utf-8 -*-
class BlogController < ApplicationController

  def index
    @blog_index = {}
    @blog_index[:cards] = [
      {title: 'John Doe',
         brief: 'Some example text some example text. John Doe is an architect and engineer',
         btn_link: '#',
         img: {
           src: 'http://static.runoob.com/images/mix/img_avatar.png',
           alt: 'Card image'
        }
      },
      {title: 'John Doe', brief: 'Some example text some example text. John Doe is an architect and engineer',btn_link: '#', img: {src: 'http://static.runoob.com/images/mix/img_avatar.png',alt: 'Card image'}},
      {title: 'John Doe', brief: 'Some example text some example text. John Doe is an architect and engineer',btn_link: '#', img: {src: 'http://static.runoob.com/images/mix/img_avatar.png',alt: 'Card image'}}
    ]

    @blog_index[:carousels] = [
      {title: '第一张图片描述标题',brief: '描述文字!', img: {src: 'http://static.runoob.com/images/mix/img_fjords_wide.jpg'}},
      {title: '第二张图片描述标题',brief: '描述文字!', img: {src: 'http://static.runoob.com/images/mix/img_nature_wide.jpg'}},
      {title: '第三张图片描述标题',brief: '描述文字!', img: {src: 'http://static.runoob.com/images/mix/img_mountains_wide.jpg'}}
    ]
  end

  def show

  end

  def test

  end

end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController

  def index
    @home_index = {}
    @home_index[:cards] = [
      {title: 'John Doe', brief: 'Some example text some example text. John Doe is an architect and engineer',btn_link: '#', img: {src: 'http://static.runoob.com/images/mix/img_avatar.png',alt: 'Card image'}},
      {title: 'John Doe', brief: 'Some example text some example text. John Doe is an architect and engineer',btn_link: '#', img: {src: 'http://static.runoob.com/images/mix/img_avatar.png',alt: 'Card image'}},
      {title: 'John Doe', brief: 'Some example text some example text. John Doe is an architect and engineer',btn_link: '#', img: {src: 'http://static.runoob.com/images/mix/img_avatar.png',alt: 'Card image'}}
    ]

    @home_index[:carousels] = [
      {title: '第一张图片描述标题',brief: '描述文字!', img: {src: 'http://static.runoob.com/images/mix/img_fjords_wide.jpg'}},
      {title: '第二张图片描述标题',brief: '描述文字!', img: {src: 'http://static.runoob.com/images/mix/img_nature_wide.jpg'}},
      {title: '第三张图片描述标题',brief: '描述文字!', img: {src: 'http://static.runoob.com/images/mix/img_mountains_wide.jpg'}}
    ]
  end 
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/index.html.haml
/ 导航栏
= render 'shared/nav'
.div{ style: "margin-top: 70px;"}
/ 轮播图
= render 'shared/carousel', carousels: @blog_index[:carousels] 
/ 卡片
= render 'shared/card', cards: @blog_index[:cards]

app/views/blog/show.html.haml
.container-fluid{style: 'height: 500px;'}
  %img{ src: 'http://static.runoob.com/images/mix/img_fjords_wide.jpg'}

app/views/blog/test.html.haml
.div
  %img{ src: 'http://static.runoob.com/images/mix/img_fjords_wide.jpg', style: 'width: 100%; height: 450px;'}
.paper
  test

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      ChernoAlpha
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container
      = yield

app/views/shared/_card.html.haml
/卡片
%div{class: "row", style: ""}
  - cards.each_with_index do |card, index|
    %div{class: "card col-6", style: 'height: 425px; border: none; margin: 5px 0px;'}
      %img{class: "card-img-top img-responsive", src: "#{card[:img][:src]}", alt: "#{card[:img][:alt]}", style: "filter: blur(0px); height: 220px; width: auto;"}

      %div{class: "card-body", style: 'background-color: rgba(175, 196, 220, 0.25);'}
        %h4{class: "card-title"}=card[:title]
        %p{class: "card-text"}=card[:brief]
        /%a{href: "#myModal", class: "btn btn-primary", data:{toggle: 'modal'}}See Profile
        /= render 'shared/modal', id: 'myModal'
        / %a{href: "#{card[:btn_link]}", class: "btn btn-primary"}See Profile
        = link_to '阅读', test_blog_index_path

app/views/shared/_carousel.html.haml
/ 轮播图 
%div{id:"demo", class:"carousel slide", data: {ride:"carousel"}}
  / 指示符 
  %ul{class:"carousel-indicators"}
    - carousels.each_with_index do |carousel, index|
      %li{data: {target:"#demo"}, data: {slide: {to: "#{index}"}}, class:"#{ index == 0 ? 'active' : ''}"}
  
  / 轮播图片 
  %div{class:"carousel-inner"}
    - carousels.each_with_index do |carousel, index|
      %div{class:"carousel-item #{ index == 0 ? 'active' : ''}"}
        %img{src:"#{carousel[:img][:src]}"}
        %div{class:"carousel-caption"}
          %h3= carousel[:title]
          %p= carousel[:brief]

    
      
  / 左右切换按钮 
  %a{class:"carousel-control-prev", href:"#demo", data:  {lide:"prev"}}
    %span{class:"carousel-control-prev-icon"}
  %a{class:"carousel-control-next", href:"#demo", data: {slide:"next"}}
    %span{class:"carousel-control-next-icon"}
  

app/views/shared/_modal.html.haml
/ 模态框 
/%div{class: "modal fade", id: "#{id}"}
%div.modal.fade{id: id}
  .modal-dialog
    .modal-content
      / 模态框头部 
      .modal-header
        %h4.modal-title
          文章标题
        %span.badge.badge-pill.badge-primary
          主要
          %span.badge.badge-light
            4
        %button.close{data:{dismiss:"modal"}}
          &times;
      / 模态框主体 
      .modal-body{style: "height: 500px;"}
        模态框内容..
      / 模态框底部 
      .modal-footer
        .input-group.mb-3
          %input.form-control{type: "text", placeholder: "此刻你在想什么.."}
          .input-group-append
            %button.btn.btn-primary
              评论
            %button.btn.btn-danger
              清空

app/views/shared/_nav.html.haml
/导航栏
%div
  %nav{class: "navbar navbar-expand-sm bg-dark navbar-dark fixed-top justify-content-center nav-justified"}
    %a{class: "navbar-brand", href: "#"}Logo

    %ul{class: "navbar-nav"}
      %li{class: "nav-item"}
        %a{class: "nav-link", href: "#"}Link
      / 只会遍历它的下级元素
      - 12.times do
        %li{class: "nav-item"}
          %a{class: "nav-link", href: "#"}Link
      %li{class: "nav-item"}
        %a{class: "nav-link", href: "#"}Last
    %form{class: "form-inline"}
      %input{class: "form-control", type: "text", placeholder: "Search"}
      %button{class: "btn btn-success", type: "button"}搜索